name: Golang apiserver

on:
  push:
    paths:
      - 'server/**'
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Verify dependencies
        run: go mod verify

      - name: build
        run: |
            go build -o bin/server
